<?php

namespace backend\module\bank\controllers;

use yii\web\Controller;
use yii\common\models\Fillq;
use yii\db\Query;

/**
 * Default controller for the `bank` module
 * 填空题题：固定模式，一个题干，一个答案
 */
class FillqController extends Controller
{
    public function actionIndex()
    {
        return "bank-fillq"; // TODO: Change the autogenerated stub
    }
    /*
     * 填空题
     */

    /**
     * fillq model
     * @property integer $fqid
     * @property string $fqitem
     * @property string $fqans
     * @property string $fqtail
     * @property string $fqrem
     * @property string $fqstatus
     */
    /*
     * 查找全部的填空题
     */
    public function actionQueryfill()
    {
        $query = (new Query())
            ->select("*")
            ->from('fillq')
            ->where(['fqstatus'=>1])
            ->all();
        return array("data"=>$query,"msg"=>"全部的填空题");
    }
    /*
     * 增加填空题：参数(题干、答案、详解、相关知识)
     */
    public function actionAddfill()
    {
        $id = (new Query())
            ->select("*")
            ->from('fillq')
            ->where(['fqstatus'=>1])
            ->count();
        $id = $id+1;
        $request = \Yii::$app->request;
        $item = $request->post('qitem');
        $ans = $request->post('ans');
        $tail = $request->post('tail');
        $rem=$request->post('rem');
        $id ="2";
        $item = "这是谁？";
        $ans ="张飞3";
        $tail = "人物形象";
        $rem ="三国";
        $query = (new Query())
            ->select('*')
            ->from('fillq')
            ->where(['fqitem'=>$item])
            ->andWhere(['fqstatus'=>1])
            ->one();
        if($query)
        {
            return array("data"=>$query,"msg"=>"该题已在题库中，请勿重复添加");
        }
        else
        {
            $updatec = \Yii::$app->db->createCommand()->insert('fillq',
                array('fqid'=>$id,'fqitem'=>$item,'fqans'=>$ans,'fqtail'=>$tail,
                    'fqrem'=>$rem,'fqstatus'=>1))->execute();
            if($updatec)
            {
                return array("data"=>$updatec,"msg"=>"插入填空题成功");
            }
            else{
                return array("data"=>$updatec,"msg"=>"插入失败，该题已插入");
            }
        }
    }
    /*
     * 删除填空题：一个函数实现
     * 给出标志：flag
     * 1:暂时删除
     * 2：永久删除
     * 实际的修改需删除变量
     */
    public function actionDeletefill()
    {
        $requset = \Yii::$app->request;
        $id = $requset->post('fid');
        $id ='2';
        $query = (new Query())
            ->select('*')
            ->from('fillq')
            ->where(['fqid'=>$id])
            ->one();
        if($query)
        {
            $flag = $requset->post('flag');
            $flag ='2';
            if($flag==1)
            {
                //暂时删除
                $updatec = \Yii::$app->db->createCommand()->update('fillq',['fqstatus'=>0],"fqid={$id}")->execute();
                if($updatec)
                {
                    return array("data"=>[$query,$updatec],"msg"=>"该填空题删除成功");
                }
                else
                {
                    return array("data"=>[$query,$updatec],"msg"=>"该填空题已删除，不用重复删除");
                }
            }
            else if($flag==2)
            {
                //永久删除
                $updatec = \Yii::$app->db->createCommand()->delete('fillq',['fqid'=>$id])->execute();
                if($updatec)
                {
                    return array("data"=>[$query,$updatec],"msg"=>"该填空题删除成功");
                }
                else
                {
                    return array("data"=>[$query,$updatec],"msg"=>"该填空题已删除，不用重复删除");
                }
            }
            else{
                return array("data"=>[$query,$flag],"msg"=>"输入错误");
            }
        }
        else
        {
            return array("data"=>$query,"msg"=>"没有找到该填空题");
        }
    }

    /*
     * 修改填空题相关内容：一个函数实现
     * 给出标志：flag
     * 1:题干
     * 2：正确选项
     * 3：详解
     * 4：相关知识推荐
     */
    public function actionChangefill()
    {
        $request = \Yii::$app->request;
        $id = $request->post('fid');
        $id = '2';
        $query = (new Query())
            ->select('*')
            ->from('fillq')
            ->where(['fqid'=>$id])
            ->andWhere(['fqstatus'=>1])
            ->one();
        if($query)
        {
            $flag = $request->post('flag');
            $flag ='4';
            if($flag==1)
            {
                //题干
                $item = $request->post('item');
                $item = "题干";
                if($item==$query['fqitem']){
                    return array("data"=>[$query,$item],"msg"=>"两次题干一致，不能修改");
                }
                else{
                    $updatec = \Yii::$app->db->createCommand()->update('fillq',['fqitem'=>$item],"fqid={$id}")->execute();
                    if($updatec)
                    {
                        return array("data"=>[$query,$item,$updatec],"msg"=>"该填空题题干修改成功");
                    }
                    else
                    {
                        return array("data"=>[$query,$item,$updatec],"msg"=>"该填空题题干已修改，不用重复修改");
                    }
                }
            }
            else if($flag==2)
            {
                //正确答案
                $ans = $request->post('ans');
                $ans = "112223";
                if($ans==$query['fqans']){
                    return array("data"=>[$query,$ans],"msg"=>"两次答案一致，不能修改");
                }
                else{
                    $updatec = \Yii::$app->db->createCommand()->update('fillq',['fqans'=>$ans],"fqid={$id}")->execute();
                    if($updatec)
                    {
                        return array("data"=>[$query,$ans,$updatec],"msg"=>"该填空题答案修改成功");
                    }
                    else
                    {
                        return array("data"=>[$query,$ans,$updatec],"msg"=>"该填空题答案已修改，不用重复修改");
                    }
                }
            }
            else if($flag==3)
            {
                //详解
                $tail = $request->post('tail');
                $tail="1111111111";
                if($tail==$query['fqtail']){
                    return array("data"=>[$query,$tail],"msg"=>"两次详解一致，不能修改");
                }
                else{
                    $updatec = \Yii::$app->db->createCommand()->update('fillq',['fqtail'=>$tail],"fqid={$id}")->execute();
                    if($updatec)
                    {
                        return array("data"=>[$query,$tail,$updatec],"msg"=>"该填空题详解修改成功");
                    }
                    else
                    {
                        return array("data"=>[$query,$tail,$updatec],"msg"=>"该填空题详解已修改，不用重复修改");
                    }
                }
            }
            else if($flag==4)
            {
                //相关知识
                $rem = $request->post('rem');
                $rem = "2344";
                if($rem==$query['fqrem']){
                    return array("data"=>[$query,$rem],"msg"=>"两次相关知识一致，不能修改");
                }
                else{
                    $updatec = \Yii::$app->db->createCommand()->update('fillq',['fqrem'=>$rem],"fqid={$id}")->execute();
                    if($updatec)
                    {
                        return array("data"=>[$query,$rem,$updatec],"msg"=>"该填空题相关知识修改成功");
                    }
                    else
                    {
                        return array("data"=>[$query,$rem,$updatec],"msg"=>"该填空题相关知识已修改，不用重复修改");
                    }
                }
            }
            else{
                return array("data"=>$query,"msg"=>"输入错误");
            }
        }
        else{
            return array("data"=>$query,"msg"=>"未查找到该填空题");
        }
    }
}