<?php

namespace backend\module\bank\controllers;

use yii\web\Controller;
use yii\common\models\Program;
use yii\db\Query;

/**
 * Default controller for the `bank` module
 * 程序题题：固定模式，一个题干，一个答案
 */
class ProgramController extends Controller
{
    public function actionIndex()
    {
        return "bank-program"; // TODO: Change the autogenerated stub
    }
    /*
     * 程序题
     */

    /**
     * program model
     * @property integer $pqid
     * @property string $pqitem
     * @property string $pqans
     * @property string $pqtail
     * @property string $pqrem
     * @property string $pqstatus
     */
    /*
     * 查找全部的程序题
     * 标志：flag
     * 1:全部的程序题
     * 2：有效的程序题
     * 3：模糊查找某题
     * 4：无效的程序题
     */
    public function actionQueryprogram()
    {
        $request = \Yii::$app->request;
        $flag = $request->post('flag');
        if ($flag == 1) {
            $query = (new Query())
                ->select("*")
                ->from('program')
                ->all();
            return array("data" => $query, "msg" => "全部的程序题");
        } else if ($flag == 2) {
            $query = (new Query())
                ->select("*")
                ->from('program')
                ->where(['pqstatus' => 1])
                ->all();
            return array("data" => $query, "msg" => "有效的程序题");
        } else if ($flag == 3) {
            $name = $request->post('name');
            $query = (new Query())
                ->select("*")
                ->from('program')
                ->where(['or',
                    ['like', 'pqitem', $name],
                    ['like', 'pqans', $name],
                    ['like', 'pqtail', $name],
                    ['like', 'pqrem', $name],
                ])
                ->all();
            return array("data" => $query, "msg" => $name . "程序题");
        } else if ($flag == 4) {
            $query = (new Query())
                ->select("*")
                ->from('program')
                ->where(['pqstatus' => 0])
                ->all();
            return array("data" => $query, "msg" => "无效的程序题");
        } else {
            return array("data" => $flag, "msg" => "输入错误");
        }
    }

    /*
     * 增加程序题：参数(题干、答案、详解、相关知识)
     * 选择：设置为四个选项，固定的模式
     */
    public function actionAddprogram()
    {
        $id = (new Query())
            ->select("*")
            ->from('program')
            ->max('pqid');
        $id = $id + 1;
        $request = \Yii::$app->request;
        $item = $request->post('qitem');
        $ans = $request->post('ans');
        $tail = $request->post('tail');
        $rem = $request->post('rem');
        $query = (new Query())
            ->select('*')
            ->from('program')
            ->where(['pqitem' => $item])
            ->one();
        if ($query) {
            return array("data" => $query, "msg" => "该题已在题库中，请勿重复添加");
        } else {
            $updatec = \Yii::$app->db->createCommand()->insert('program',
                array('pqid' => $id, 'pqitem' => $item, 'pqans' => $ans, 'pqtail' => $tail,
                    'pqrem' => $rem, 'pqstatus' => 1))->execute();
            if ($updatec) {
                return array("data" => $updatec, "msg" => "插入程序题成功");
            } else {
                return array("data" => $updatec, "msg" => "插入失败，该题已插入");
            }
        }
    }

    /*
     * 删除程序题：一个函数实现
     * 给出标志：flag
     * 1:暂时删除
     * 2：永久删除
     * 实际的修改需删除变量
     */
    public function actionDelete()
    {
        $requset = \Yii::$app->request;
        $id = $requset->post('fid');
        $query = (new Query())
            ->select('*')
            ->from('program')
            ->where(['pqid' => $id])
            ->one();
        if ($query) {
            $flag = $requset->post('flag');
            if ($flag == 1) {
                //暂时删除
                $updatec = \Yii::$app->db->createCommand()->update('program', ['pqstatus' => 0], "pqid={$id}")->execute();
                if ($updatec) {
                    return array("data" => [$query, $updatec], "msg" => "该程序题删除成功");
                } else {
                    return array("data" => [$query, $updatec], "msg" => "该程序题已删除，不用重复删除");
                }
            } else if ($flag == 2) {
                //永久删除
                $updatec = \Yii::$app->db->createCommand()->delete('program', ['pqid' => $id])->execute();
                if ($updatec) {
                    return array("data" => [$query, $updatec], "msg" => "该程序题永久删除成功");
                } else {
                    return array("data" => [$query, $updatec], "msg" => "该程序题已永久删除，不用重复删除");
                }
            } else {
                return array("data" => [$query, $flag], "msg" => "输入错误");
            }

        } else {
            return array("data" => $query, "msg" => "没有找到该程序题");
        }
    }

    /*
     * 修改程序题相关内容：一个函数实现
     * 给出标志：flag
     * 1:题干
     * 2：正确选项
     * 3：详解
     * 4：相关知识推荐
     * 5：状态
     * 实际的修改需删除变量
     */
    public function actionChange()
    {
        $request = \Yii::$app->request;
        $id = $request->post('cid');
        $query = (new Query())
            ->select('*')
            ->from('program')
            ->where(['pqid' => $id])
            ->one();
        if ($query) {
            $flag = $request->post('flag');
            if ($flag == 1) {
                //题干
                $item = $request->post('item');
                if ($item == $query['pqitem']) {
                    return array("data" => [$query, $item], "msg" => "两次题干一致，不能修改");
                } else {
                    $updatec = \Yii::$app->db->createCommand()->update('program', ['pqitem' => $item], "pqid={$id}")->execute();
                    if ($updatec) {
                        return array("data" => [$query, $item, $updatec], "msg" => "该程序题题干修改成功");
                    } else {
                        return array("data" => [$query, $item, $updatec], "msg" => "该程序题题干已修改，不用重复修改");
                    }
                }
            }
            else if ($flag == 2) {
                //正确答案
                $ans = $request->post('ans');
                if ($ans == $query['pqans']) {
                    return array("data" => [$query, $ans], "msg" => "两次答案一致，不能修改");
                } else {
                    $updatec = \Yii::$app->db->createCommand()->update('program', ['pqans' => $ans], "pqid={$id}")->execute();
                    if ($updatec) {
                        return array("data" => [$query, $ans, $updatec], "msg" => "该程序题答案修改成功");
                    } else {
                        return array("data" => [$query, $ans, $updatec], "msg" => "该程序题答案已修改，不用重复修改");
                    }
                }
            }
            else if ($flag == 3) {
                //详解
                $tail = $request->post('tail');
                if ($tail == $query['pqtail']) {
                    return array("data" => [$query, $tail], "msg" => "两次详解一致，不能修改");
                } else {
                    $updatec = \Yii::$app->db->createCommand()->update('program', ['pqtail' => $tail], "pqid={$id}")->execute();
                    if ($updatec) {
                        return array("data" => [$query, $tail, $updatec], "msg" => "该程序题详解修改成功");
                    } else {
                        return array("data" => [$query, $tail, $updatec], "msg" => "该程序题详解已修改，不用重复修改");
                    }
                }
            }
            else if ($flag == 4) {
                //相关知识
                $rem = $request->post('rem');
                if ($rem == $query['pqrem']) {
                    return array("data" => [$query, $rem], "msg" => "两次相关知识一致，不能修改");
                } else {
                    $updatec = \Yii::$app->db->createCommand()->update('program', ['pqrem' => $rem], "pqid={$id}")->execute();
                    if ($updatec) {
                        return array("data" => [$query, $rem, $updatec], "msg" => "该程序题相关知识修改成功");
                    } else {
                        return array("data" => [$query, $rem, $updatec], "msg" => "该程序题相关知识已修改，不用重复修改");
                    }
                }
            }
            else if ($flag == 5) {
//                状态
                $updatec = \Yii::$app->db->createCommand()->update('program', ['pqstatus' => 1], "pqid={$id}")->execute();
                if ($updatec) {
                    return array("data" => [$query, $updatec], "msg" => "该程序题状态修改成功");
                } else {
                    return array("data" => [$query, $updatec], "msg" => "该程序题状态已修改，不用重复修改");
                }
            } else {
                return array("data" => $query, "msg" => "输入错误");
            }
        } else {
            return array("data" => $query, "msg" => "未查找到该程序题");
        }
    }
    public function actionImportexcel()
    {
        $request = \Yii::$app->request;
        $data = $request->post('data');
        $data = json_decode($data,true);
        for($i=0;$i<count($data);$i++)
        {
            $item= isset($data[$i]['item'])?$data[$i]['item']:"";
            $ans= isset($data[$i]['ans'])?$data[$i]['ans']:"";
            $tail = isset($data[$i]['tail'])?$data[$i]['tail']:"";
            $rem = isset($data[$i]['rem'])?$data[$i]['rem']:"";
            $query = (new Query())
                ->select('*')
                ->from('program')
                ->where(['pqitem'=>$item])
                ->one();
            $id = (new Query())
                ->select("*")
                ->from('program')
                ->where(['pqstatus'=>1])
                ->max('pqid');
            $id = $id+1;
            if($query == null)
            {
                $updatec = \Yii::$app->db->createCommand()->insert('program',
                    array('pqid'=>$id,'pqitem'=>$item,'pqans'=>$ans,'pqtail'=>$tail,
                        'pqrem'=>$rem,'pqstatus'=>1))->execute();
            }
        }
        return array("data"=>$data,"msg"=>"导入成功");
    }
}