<?php
namespace backend\module\home\controllers;

use yii\db\Exception;
use yii\web\Controller;
use yii\common\models\User;
use yii\web\Response;
use yii\web\Request;
use yii\db\Query;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;
use yii\filters\Cors;
use yii\behaviors\TimestampBehavior;
use backend\module\home\controllers\IndexController;

/**
 * Default controller for the `home` module
 */
class UserController extends Controller
{
    public function actionIndex()
    {
        return "user"; // TODO: Change the autogenerated stub
    }

    //用户管理，用于普通人身份
    //设置功能：修改密码、返回个人信息

    /*
     * 修改密码：参数（用户id/用户名）
     */
    public function actionChangepassword()
    {
//        $request = \Yii::$app->request;
//        $username = $request->post('username');
//        $userid = $request->post('userid');
//        两者知道一个即可
        $userid = "2";
        $password="zhouqing";

        $query = (new Query())
            ->select('*')
            ->from('user')
            ->where(['id'=>$userid])
            ->andWhere(['status'=>1])
            ->one();
        if($query)
        {
            $passwordD = \backend\module\home\controllers\IndexController::PasswordDecry($query['password']);
            if($password == $passwordD)
            {
                return array("data"=>[$passwordD,$password],"msg"=>"和原始密码一致");
            }
            else{
                $passwordE = \backend\module\home\controllers\IndexController::PasswordEncry($password);
                $update=\Yii::$app->db->createCommand()->update('user',['password'=>$passwordE],"id={$userid}")->execute();
                if($update)
                {
                    return array("data"=>[$update,$passwordE,$password],"msg"=>"修改密码成功");
                }
                else{
                    return array("data"=>[$update,$password,$passwordE],"msg"=>"修改密码失败");
                }
            }
        }
        else{
            return array("data"=>$query,"msg"=>"未找到该用户");
        }
    }
    /*
     * 返回个人信息：参数（用户id或者用户名）
     */
    public function actionGetuser()
    {
//        $request = \Yii::$app->request;
//        $username = $request->post('username');
//        $userid = $request->post('userid');
        $userid = "2";
        $query = (new Query())
            ->select("*")
            ->from('user')
            ->where(['id'=>$userid])
            ->andWhere(['status'=>1])
            ->one();
        if($query)
        {
            return array("data"=>$query,"msg"=>"查找到该用户信息");
        }
        else
        {
            return array("data"=>$query,"msg"=>"未找到该用户");
        }
    }


    //用户管理，用于管理员身份
    //设置功能：查看所有用户信息(所有信息、管理层信息、普通用户信息)、添加用户、修改（用户名、密码）、删除用户（暂时删除或者永久删除）、变更身份


    /*
    *查找所有用户，是有效的用户
     * 显示用户信息时，不保存用户的密码信息，仅显示用户名、角色
     */
    public function actionQuery()
    {
        $query = (new Query())
            ->select('*')
            ->from('user')
            ->Where(['status'=> 1])
            ->all();
        return array("data"=>$query,"msg"=>"所有用户");
    }
    /*
     * 查看管理层信息
     */
    public function actionQueryrole2()
    {
        $query = (new Query())
            ->select('*')
            ->from('user')
            ->where(['role'=>2])
            ->andWhere(['status'=> 1])
            ->all();
        return array("data"=>$query,"msg"=>"管理层用户信息");
    }
    /*
     * 查看普通用户信息
     */
    public function actionQueryrole3()
    {
        $query = (new Query())
            ->select('*')
            ->from('user')
            ->where(['role'=>3])
            ->andWhere(['status'=> 1])
            ->all();
        return array("data"=>$query,"msg"=>"普通用户信息");
    }
    /*
     * 添加用户
     * 其中用户id、用户名、password、role、status是必不可少的内容
     * id为关键码，不可重复
     * 其中默认密码为123456、角色为3普通用户（可前端设计下拉框选择添加用户的身份）
     */
    public function actionAdduser()
    {
        $id = '10';
        $username="2019113058";
        $password="123456";
        $role = 3;
        $status=1;
//        $request = \Yii::$app->request;
//        $username = $request->post('username');
//        $password = $request->post('password');
//        $role = $request->post('role');
//        $userid = (new Query())
//            ->select('*')
//            ->from('user')
//            ->andWhere(['status' =>1])
//            ->count();
//        $id = $userid +1;
        //如果用户名已存在判断该用户已经添加过了，不能添加
        $query = (new Query())
            ->select('*')
            ->from('user')
            ->Where(['username'=> $username])
            ->andWhere(['status'=> 1])
            ->one();
        if($query){
            return array("data"=>[$query],"msg"=>"该用户名已存在，不能再添加");
        }
        $insertU = \Yii::$app->db->createCommand()->insert('user',array('id'=>$id,'username'=>$username,'password'=>$password,'role'=>$role,
            'status'=>$status))->execute();
        if($insertU)
        {
            return array("data"=>[$username,$id],"msg"=>"用户添加成功");
        }
        else
        {
            return array("data"=>[$username,$id],"msg"=>"用户添加失败");
        }
    }
    /*
     * 用户删除，删除分两种：暂时删除的和永久删除
     * 数据库中的数据很多时候不是直接删除，而是将其身份隐藏，是为了数据保持一定的有效期.即为暂时删除，
     */
    public function actionDeleteuser()
    {
//        $request=\Yii::$app->request;
//        $userid=$request->post("userid");
        $userid = '10';
        $query = (new Query())
            ->select('*')
            ->from('user')
            ->Where(['id'=>$userid])
            ->andWhere(['status'=>1])
            ->one();
        if($query)
        {
            $updateU = \Yii::$app->db->createCommand()->update('user', ['status' => 0], "id={$userid}")->execute();
            if($updateU)
            {
                return array("data"=>[$query,$updateU],"msg"=>"该用户已删除");
            }
            else
            {
                return array("data"=>[$query,$updateU],"msg"=>"该用户没有删除成功");
            }
        }
        else{
            return array("data"=>[],"msg"=>"没有找到该用户");
        }
    }
    /*
     * 用户永久删除，在数据库中永久删除
     */
    public function actionDeleteusers()
    {
//        $requests = \Yii::$app->request;
//        $userids=$requests->post("userid");
        $userids = "10";
        $querys = (new Query())
            ->select('*')
            ->from('user')
            ->Where(['id'=>$userids])
//            ->andWhere(['status'=>1])
            ->one();
        if($querys)
        {
            $updateUs = \Yii::$app->db->createCommand()->delete('user',['id'=>$userids])->execute();
            if($updateUs)
            {
                return array("data"=>[$querys,$updateUs],"msg"=>"该用户已永久删除");
            }
            else
            {
                return array("data"=>[$querys,$updateUs],"msg"=>"该用户没有永久删除成功");
            }
        }
        else{
            return array("data"=>[],"msg"=>"没有找到该用户");
        }
    }
    /*
     * 修改用户信息
     */
    public function actionChangeuser()
    {
        $userid = "10";
        $username = "aaaasomethings";
        $password="aaaaa人民出版社s";
        $role="aasomes";
//        $request = \Yii::$app->request;
//        $userid=$request->post('userid');
//        $username = $request->post('username');
//        $publish = $request->post('publish');
//        $author=$request->post("author");
//        $about=$request->post("about");
//        $userid = (new Query())
//            ->select('*')
//            ->from('user')
//            ->andWhere(['status' =>1])
//            ->count();
//        $userid = $userid +1;
        $query = (new Query())
            ->select('*')
            ->from('user')
            ->Where(['id'=>$userid])
            ->andWhere(['status'=>1])
            ->one();
        if($query)
        {
            $updateU = \Yii::$app->db->createCommand()->update('user', ['username'=>$username,
                'password'=>$password,'role'=>$role], "id={$userid}")->execute();
            if($updateU)
            {
                return array("data"=>[$query,$updateU],"msg"=>"该用户修改成功");
            }
            else
            {
                return array("data"=>[$query,$updateU],"msg"=>"该用户已经修改");
            }
        }
        else{
            return array("data"=>[],"msg"=>"没有找到该用户");
        }
    }
    /*
     * 变更用户身份：role
     * 参数：role
     */
    public function actionChangerole()
    {
//        $request = \Yii::$app->request;
//        $userid=$request->post('userid');
//        $role = $request->post('role');
        $userid = "1";
        $role =1;
        $query = (new Query())
            ->select("*")
            ->from("user")
            ->where(['id'=>$userid])
            ->andWhere(['status'=>1])
            ->one();
        if($query)
        {
            $update = \Yii::$app->db->createCommand()->update('user',['role'=>$role],"id={$userid}")->execute();
            if($update)
            {
                return array("data"=>[$query,$update],"msg"=>"用户角色修改完成");
            }
            else{
                return array("data"=>[$query,$update],"msg"=>"用户角色修改失败,该用户已是该身份");
            }
        }
        else{
            return array("data"=>$query,"msg"=>"未找到该用户");
        }
    }
}